export const SITE_URL = "https://www.mad-ski.co.kr";

export const SITE = {
  name: "MAD_INTER SKI",
  legalName: "MAD_INTER SKI",
  title: "비발디파크 스키 강습 MAD_INTER SKI",
  description:
    "대명 소노벨 비발디파크 스키 강습 전문 MAD_INTER SKI. 장우진 감독이 성인, 주니어, 초급부터 카빙·숏턴까지 영상 분석과 무전 피드백으로 자세를 교정합니다.",
  phone: "010-2007-2883",
  telephone: "+82-10-2007-2883",
  kakao: "mvp8917",
  instagram: "https://instagram.com/mad_skiii",
  youtube: "https://www.youtube.com/channel/UCZRwm9Z2AtsQqPTsI6_slwQ",
  logo: `${SITE_URL}/images/logo.jpeg`,
  image: `${SITE_URL}/images/main.jpeg`,
  address: {
    streetAddress: "서면 한치골길 262",
    addressLocality: "홍천군",
    addressRegion: "강원특별자치도",
    postalCode: "25102",
    addressCountry: "KR",
  },
  locationName: "대명 소노벨 비발디파크",
  businessRegistrationNumber: "834-62-00906",
  mailOrderSalesNumber: "2026-강원춘천-0697",
  keywords: [
    "비발디파크 스키 강습",
    "비발디파크 스키강습",
    "비발디파크 어린이 스키 강습",
    "비발디파크 주니어 스키 강습",
    "비발디파크 성인 스키 강습",
    "비발디파크 스키 레슨",
    "비발디파크 스키스쿨",
    "대명 비발디파크 스키 강습",
    "대명 비발디파크 스키강습",
    "소노벨 비발디파크 스키 강습",
    "소노벨 비발디파크 스키",
    "홍천 스키 강습",
    "홍천 스키강습",
    "강원도 스키 강습",
    "강원도 스키강습",
    "어린이 스키 강습",
    "어린이 스키강습",
    "주니어 스키 강습",
    "주니어 스키강습",
    "성인 스키 강습",
    "성인 스키강습",
    "스키 자세교정",
    "스키 카빙 강습",
    "스키 숏턴 강습",
    "장우진 스키",
    "MAD_INTER SKI",
    "매드인터스키",
  ],
};
